baseURL = "https://xgupta.github.io/"
languageCode = "en-us"
title = "A minimal Hugo website"
theme = "hugo-xmin"

googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$"]
footnotereturnlinkcontents = "↩"

[permalinks]
  note = "/note/:year/:month/:day/:slug/"
  post = "/post/:year/:month/:day/:slug/"

[menu]

  [[menu.main]]
    name = "Home"
    url = ""
    weight = 1

  [[menu.main]]
    name = "About"
    url = "about/"
    weight = 2

[params]
  description = "A website built through Hugo."

[markup]
  [markup.highlight]
    codeFences = false

  [markup.goldmark.renderer]
    unsafe = true

  [markup.goldmark.extensions.passthrough]
    enable = true

    [markup.goldmark.extensions.passthrough.delimiters]
      block = [["\\[", "\\]"], ["$$", "$$"]]
      inline = [["\\(", "\\)"]]
